<?php

return [
    'reasons-by-brand' => [
        'drumeo' => [
            'no-time' => 'no-time',
            'too-expensive' => 'too-expensive',
            'dont-use-enough' => 'dont-use-enough',
            'couldnt-find-lessons' => 'couldnt-find-lessons',
            'too-easy' => 'too-easy',
            'too-difficult' => 'too-difficult',
            'lesson-quality' => 'lesson-quality',
            'dont-like-website' => 'dont-like-website',
            'technical-problems' => 'technical-problems',
            'other-drum-lessons' => 'other-drum-lessons',
            'other-reason' => 'other-reason',
        ],
        'pianote' => [
            'no-time' => 'no-time',
            'too-expensive' => 'too-expensive',
            'dont-use-enough' => 'dont-use-enough',
            'couldnt-find-lessons' => 'couldnt-find-lessons',
            'too-easy' => 'too-easy',
            'too-difficult' => 'too-difficult',
            'lesson-quality' => 'lesson-quality',
            'dont-like-website' => 'dont-like-website',
            'technical-problems' => 'technical-problems',
            'other-piano-lessons' => 'other-piano-lessons',
            'other-reason' => 'other-reason',
        ],
        'guitareo' => [
            'no-time' => 'no-time',
            'too-expensive' => 'too-expensive',
            'dont-use-enough' => 'dont-use-enough',
            'couldnt-find-lessons' => 'couldnt-find-lessons',
            'too-easy' => 'too-easy',
            'too-difficult' => 'too-difficult',
            'lesson-quality' => 'lesson-quality',
            'dont-like-website' => 'dont-like-website',
            'technical-problems' => 'technical-problems',
            'other-piano-lessons' => 'other-piano-lessons',
            'other-reason' => 'other-reason',
        ],
        'singeo' => [
            'no-time' => 'no-time',
            'too-expensive' => 'too-expensive',
            'dont-use-enough' => 'dont-use-enough',
            'couldnt-find-lessons' => 'couldnt-find-lessons',
            'too-easy' => 'too-easy',
            'too-difficult' => 'too-difficult',
            'lesson-quality' => 'lesson-quality',
            'dont-like-website' => 'dont-like-website',
            'technical-problems' => 'technical-problems',
            'other-piano-lessons' => 'other-piano-lessons',
            'other-reason' => 'other-reason',
        ],
    ],
    'reason-maps-by-brand' => [
        'drumeo' => [
            'no-time' => 'Drumming is not a priority for me right now',
            'too-expensive' => 'I’m cutting expenses for a little while',
            'dont-use-enough' => 'Other activities currently have my attention',
            'couldnt-find-lessons' => 'I don’t know what I’m doing. I probably need someone to help me out',
            'too-easy' => 'Everything I’ve seen, I can do already. I’m looking for more advanced lessons',
            'too-difficult' => 'I’m having a hard time with online learning',
            'lesson-quality' => 'I want feedback on my drumming which I can’t get with Drumeo',
            'dont-like-website' => 'I’m not making any progress with your website',
            'technical-problems' => 'I’m having technical problems',
            'other-drum-lessons' => 'I’m using other drum lessons',
            'other-reason' => 'Other reason',
        ],
        'pianote' => [
            'no-time' => 'I’m too busy to practice piano',
            'too-expensive' => 'It’s a bit too expensive at the moment',
            'dont-use-enough' => 'I don’t use it enough',
            'couldnt-find-lessons' => 'I couldn’t find the lessons I wanted',
            'too-easy' => 'The lessons are too easy',
            'too-difficult' => 'The lessons are too difficult',
            'lesson-quality' => 'I don’t like the lesson quality',
            'dont-like-website' => 'I don’t like the website or app',
            'technical-problems' => 'I’m having technical problems',
            'other-piano-lessons' => 'I’m using other piano lessons',
            'other-reason' => 'Other reason',
        ],
        'guitareo' => [
            'no-time' => 'I’m too busy to practice',
            'too-expensive' => 'It’s a bit too expensive at the moment',
            'dont-use-enough' => 'I don’t use it enough',
            'couldnt-find-lessons' => 'I couldn’t find the lessons I wanted',
            'too-easy' => 'The lessons are too easy',
            'too-difficult' => 'The lessons are too difficult',
            'lesson-quality' => 'I don’t like the lesson quality',
            'dont-like-website' => 'I don’t like the website or app',
            'technical-problems' => 'I’m having technical problems',
            'other-piano-lessons' => 'I’m using other lessons',
            'other-reason' => 'Other reason',
        ],
        'singeo' => [
            'no-time' => 'I’m too busy to practice',
            'too-expensive' => 'It’s a bit too expensive at the moment',
            'dont-use-enough' => 'I don’t use it enough',
            'couldnt-find-lessons' => 'I couldn’t find the lessons I wanted',
            'too-easy' => 'The lessons are too easy',
            'too-difficult' => 'The lessons are too difficult',
            'lesson-quality' => 'I don’t like the lesson quality',
            'dont-like-website' => 'I don’t like the website or app',
            'technical-problems' => 'I’m having technical problems',
            'other-piano-lessons' => 'I’m using other lessons',
            'other-reason' => 'Other reason',
        ],
    ],
    'previous-version-reason-maps-by-brand' => [
        'drumeo' => [
            'no-time' => "I don’t have the time",
            'too-expensive' => "It’s too expensive",
            'dont-use-enough' => "I don’t use it enough",
            'other-drum-lessons' => "I’m using other drum lessons",
            'couldnt-find-lessons' => "I couldn’t find the lessons I wanted",
            'too-easy' => "The lessons are too easy",
            'too-difficult' => "The lessons are too difficult",
            'lesson-quality' => "I don’t like the lesson quality",
            'dont-like-website' => "I don’t like the website or app",
            'technical-problems' => "I’m having technical problems",
        ],
        'pianote' => [
            'no-time' => 'I don\'t have the time.',
            'too-expensive' => 'It\'s too expensive.',
            'dont-use-enough' => 'I\'m not using it.',
            'couldnt-find-lessons' => 'I don\'t know how to use it.',
            'too-easy' => 'The lessons are too easy.',
            'too-difficult' => 'The lessons are too difficult.',
            // 'lesson-quality' => '',     # didn't exist previously
            // 'dont-like-website' => '',  # didn't exist previously
            // 'technical-problems' => '', # didn't exist previously
            // 'other-piano-lessons' => '', # didn't exist previously
            'other-reason' => 'Other',
        ],
        'guitareo' => [
            'noTime' => 'I don\'t have the time.',
            'notUsing' => 'I\'m not using it.',
            'tooEasy' => 'The lessons are too easy.',
            'tooDifficult' => 'The lessons are too difficult.',
            'tooExpensive' => 'It\'s too expensive.',
            'dontKnow' => 'I don\'t know how to use it.',
            'other' => 'Other',
        ],
        'singeo' => [
            'noTime' => 'I don\'t have the time.',
            'notUsing' => 'I\'m not using it.',
            'tooEasy' => 'The lessons are too easy.',
            'tooDifficult' => 'The lessons are too difficult.',
            'tooExpensive' => 'It\'s too expensive.',
            'dontKnow' => 'I don\'t know how to use it.',
            'other' => 'Other',
        ],
    ],
];